/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnerRegistrationRouteImport } from './routes/partner-registration'
import { Route as PRouteImport } from './routes/p'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPartnersRouteImport } from './routes/_app/partners'
import { Route as AppIntegrationRouteImport } from './routes/_app/integration'
import { Route as AppInspectionsRouteImport } from './routes/_app/inspections'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppBrokersRouteImport } from './routes/_app/brokers'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppRentalsIndexRouteImport } from './routes/_app/rentals/index'
import { Route as AppPropertiesIndexRouteImport } from './routes/_app/properties/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppRentalsHomologationRouteImport } from './routes/_app/rentals/homologation'
import { Route as AppPropertiesIdRouteImport } from './routes/_app/properties/$id'
import { Route as AppDocumentsTemplatesRouteImport } from './routes/_app/documents/templates'
import { Route as AppDocumentsNewRouteImport } from './routes/_app/documents/new'

const PartnerRegistrationRoute = PartnerRegistrationRouteImport.update({
  id: '/partner-registration',
  path: '/partner-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PRoute = PRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationRoute = AppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppBrokersRoute = AppBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppRentalsIndexRoute = AppRentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppRentalsHomologationRoute = AppRentalsHomologationRouteImport.update({
  id: '/rentals/homologation',
  path: '/rentals/homologation',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsTemplatesRoute = AppDocumentsTemplatesRouteImport.update({
  id: '/documents/templates',
  path: '/documents/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsNewRoute = AppDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/p': typeof PRoute
  '/partner-registration': typeof PartnerRegistrationRoute
  '/brokers': typeof AppBrokersRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/inspections': typeof AppInspectionsRoute
  '/integration': typeof AppIntegrationRoute
  '/partners': typeof AppPartnersRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/users': typeof AppUsersRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/documents/templates': typeof AppDocumentsTemplatesRoute
  '/properties/$id': typeof AppPropertiesIdRoute
  '/rentals/homologation': typeof AppRentalsHomologationRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/properties/': typeof AppPropertiesIndexRoute
  '/rentals/': typeof AppRentalsIndexRoute
  '/sales/': typeof AppSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/p': typeof PRoute
  '/partner-registration': typeof PartnerRegistrationRoute
  '/brokers': typeof AppBrokersRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/inspections': typeof AppInspectionsRoute
  '/integration': typeof AppIntegrationRoute
  '/partners': typeof AppPartnersRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/users': typeof AppUsersRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/documents/templates': typeof AppDocumentsTemplatesRoute
  '/properties/$id': typeof AppPropertiesIdRoute
  '/rentals/homologation': typeof AppRentalsHomologationRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/properties': typeof AppPropertiesIndexRoute
  '/rentals': typeof AppRentalsIndexRoute
  '/sales': typeof AppSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/p': typeof PRoute
  '/partner-registration': typeof PartnerRegistrationRoute
  '/_app/brokers': typeof AppBrokersRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/inspections': typeof AppInspectionsRoute
  '/_app/integration': typeof AppIntegrationRoute
  '/_app/partners': typeof AppPartnersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/documents/new': typeof AppDocumentsNewRoute
  '/_app/documents/templates': typeof AppDocumentsTemplatesRoute
  '/_app/properties/$id': typeof AppPropertiesIdRoute
  '/_app/rentals/homologation': typeof AppRentalsHomologationRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/properties/': typeof AppPropertiesIndexRoute
  '/_app/rentals/': typeof AppRentalsIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/p'
    | '/partner-registration'
    | '/brokers'
    | '/clients'
    | '/dashboard'
    | '/finance'
    | '/inspections'
    | '/integration'
    | '/partners'
    | '/settings'
    | '/support'
    | '/users'
    | '/documents/new'
    | '/documents/templates'
    | '/properties/$id'
    | '/rentals/homologation'
    | '/documents/'
    | '/properties/'
    | '/rentals/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/p'
    | '/partner-registration'
    | '/brokers'
    | '/clients'
    | '/dashboard'
    | '/finance'
    | '/inspections'
    | '/integration'
    | '/partners'
    | '/settings'
    | '/support'
    | '/users'
    | '/documents/new'
    | '/documents/templates'
    | '/properties/$id'
    | '/rentals/homologation'
    | '/documents'
    | '/properties'
    | '/rentals'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/p'
    | '/partner-registration'
    | '/_app/brokers'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/finance'
    | '/_app/inspections'
    | '/_app/integration'
    | '/_app/partners'
    | '/_app/settings'
    | '/_app/support'
    | '/_app/users'
    | '/_app/documents/new'
    | '/_app/documents/templates'
    | '/_app/properties/$id'
    | '/_app/rentals/homologation'
    | '/_app/documents/'
    | '/_app/properties/'
    | '/_app/rentals/'
    | '/_app/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PRoute: typeof PRoute
  PartnerRegistrationRoute: typeof PartnerRegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partner-registration': {
      id: '/partner-registration'
      path: '/partner-registration'
      fullPath: '/partner-registration'
      preLoaderRoute: typeof PartnerRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integration': {
      id: '/_app/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AppIntegrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspections': {
      id: '/_app/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brokers': {
      id: '/_app/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof AppBrokersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rentals/': {
      id: '/_app/rentals/'
      path: '/rentals'
      fullPath: '/rentals/'
      preLoaderRoute: typeof AppRentalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rentals/homologation': {
      id: '/_app/rentals/homologation'
      path: '/rentals/homologation'
      fullPath: '/rentals/homologation'
      preLoaderRoute: typeof AppRentalsHomologationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/$id': {
      id: '/_app/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/templates': {
      id: '/_app/documents/templates'
      path: '/documents/templates'
      fullPath: '/documents/templates'
      preLoaderRoute: typeof AppDocumentsTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/new': {
      id: '/_app/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AppDocumentsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBrokersRoute: typeof AppBrokersRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppIntegrationRoute: typeof AppIntegrationRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppUsersRoute: typeof AppUsersRoute
  AppDocumentsNewRoute: typeof AppDocumentsNewRoute
  AppDocumentsTemplatesRoute: typeof AppDocumentsTemplatesRoute
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
  AppRentalsHomologationRoute: typeof AppRentalsHomologationRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
  AppRentalsIndexRoute: typeof AppRentalsIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrokersRoute: AppBrokersRoute,
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppIntegrationRoute: AppIntegrationRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppUsersRoute: AppUsersRoute,
  AppDocumentsNewRoute: AppDocumentsNewRoute,
  AppDocumentsTemplatesRoute: AppDocumentsTemplatesRoute,
  AppPropertiesIdRoute: AppPropertiesIdRoute,
  AppRentalsHomologationRoute: AppRentalsHomologationRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
  AppRentalsIndexRoute: AppRentalsIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PRoute: PRoute,
  PartnerRegistrationRoute: PartnerRegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
