/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppIntegrationRouteImport } from './routes/_app/integration'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppBrokersRouteImport } from './routes/_app/brokers'
import { Route as AppRentalsIndexRouteImport } from './routes/_app/rentals/index'
import { Route as AppPropertiesIndexRouteImport } from './routes/_app/properties/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppPropertiesIdRouteImport } from './routes/_app/properties/$id'
import { Route as AppDocumentsTemplatesRouteImport } from './routes/_app/documents/templates'
import { Route as AppDocumentsNewRouteImport } from './routes/_app/documents/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationRoute = AppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppBrokersRoute = AppBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => AppRoute,
} as any)
const AppRentalsIndexRoute = AppRentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsTemplatesRoute = AppDocumentsTemplatesRouteImport.update({
  id: '/documents/templates',
  path: '/documents/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsNewRoute = AppDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/brokers': typeof AppBrokersRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/integration': typeof AppIntegrationRoute
  '/settings': typeof AppSettingsRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/documents/templates': typeof AppDocumentsTemplatesRoute
  '/properties/$id': typeof AppPropertiesIdRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/properties/': typeof AppPropertiesIndexRoute
  '/rentals/': typeof AppRentalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/brokers': typeof AppBrokersRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/integration': typeof AppIntegrationRoute
  '/settings': typeof AppSettingsRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/documents/templates': typeof AppDocumentsTemplatesRoute
  '/properties/$id': typeof AppPropertiesIdRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/properties': typeof AppPropertiesIndexRoute
  '/rentals': typeof AppRentalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/brokers': typeof AppBrokersRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/integration': typeof AppIntegrationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/documents/new': typeof AppDocumentsNewRoute
  '/_app/documents/templates': typeof AppDocumentsTemplatesRoute
  '/_app/properties/$id': typeof AppPropertiesIdRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/properties/': typeof AppPropertiesIndexRoute
  '/_app/rentals/': typeof AppRentalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/brokers'
    | '/clients'
    | '/dashboard'
    | '/integration'
    | '/settings'
    | '/documents/new'
    | '/documents/templates'
    | '/properties/$id'
    | '/documents/'
    | '/properties/'
    | '/rentals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/brokers'
    | '/clients'
    | '/dashboard'
    | '/integration'
    | '/settings'
    | '/documents/new'
    | '/documents/templates'
    | '/properties/$id'
    | '/documents'
    | '/properties'
    | '/rentals'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/brokers'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/integration'
    | '/_app/settings'
    | '/_app/documents/new'
    | '/_app/documents/templates'
    | '/_app/properties/$id'
    | '/_app/documents/'
    | '/_app/properties/'
    | '/_app/rentals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integration': {
      id: '/_app/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AppIntegrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brokers': {
      id: '/_app/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof AppBrokersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rentals/': {
      id: '/_app/rentals/'
      path: '/rentals'
      fullPath: '/rentals/'
      preLoaderRoute: typeof AppRentalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/$id': {
      id: '/_app/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/templates': {
      id: '/_app/documents/templates'
      path: '/documents/templates'
      fullPath: '/documents/templates'
      preLoaderRoute: typeof AppDocumentsTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/new': {
      id: '/_app/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AppDocumentsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBrokersRoute: typeof AppBrokersRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationRoute: typeof AppIntegrationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppDocumentsNewRoute: typeof AppDocumentsNewRoute
  AppDocumentsTemplatesRoute: typeof AppDocumentsTemplatesRoute
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
  AppRentalsIndexRoute: typeof AppRentalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrokersRoute: AppBrokersRoute,
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationRoute: AppIntegrationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppDocumentsNewRoute: AppDocumentsNewRoute,
  AppDocumentsTemplatesRoute: AppDocumentsTemplatesRoute,
  AppPropertiesIdRoute: AppPropertiesIdRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
  AppRentalsIndexRoute: AppRentalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
